language: python

python:
    - "2.6"
    - "2.7"

branches:
    only:
        - master
        - develop

install: 
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib; fi"
    - pip install -IM -r requirements.txt

script: python manage.py test -c base.config.test
