language: python

python:
    - "2.7"
    - "3.2"

branches:
    only:
        - master
        - develop

install: pip install -IM -r requirements.txt

script: python manage.py test -c base.config.test
